### ISSUE TITLE
Animation Slowing down typing & accuracy

### ISSUE THREAD

**Issue by devanshuyadav** [FurqanAnwar/Typing-Simulator#14]
For typing speeds <30 WPM, it works just fine. But as speed increases, It seems to hinder the user's typing. 
Typer would already type the word but it doesn't record until the animation has stopped.

**Comment by FurqanAnwar** [comment]
Thank you for reporting this bug , see that's an issue because of the animation I'm applying, the animation need to have 0.8s pause in between typing when popping off the word and right now we are not restricting our user to hold on for 0.8s that what causing the issue here.
There are `2 solutions` to this problem:

**1:** We need to change the animation so every thing will work fine speed won't be a matter any more user can type up to > 50WPM as well but the animation is the main reason which separate this project from other typing masters out there so we can't change the animation because it is the foundation of this project.

**2:** We can restrict user input for that 0.8s so that user input is counted only after the animation ends.

**Comment by yashchaudhari008** [comment]
I guess this same issue is causing #7

**Comment by devanshuyadav** [comment]
@yashchaudhari008 Yes it could be causing that
@FurqanAnwar I've fixed this issue, and the words bounce too quickly (100ms) . If you want me to add it then I'll create one PR.

**Comment by devanshuyadav** [comment]
https://user-images.githubusercontent.com/76938941/135979026-9347614b-d2fa-482e-916a-252640126ecf.mp4

It's at 100ms in the video. We can find a time that works for the animation as well as doesn't hinder the typing.

**Comment by yashchaudhari008** [comment]
>  typing-simulator-fix.mp4 
> It's at 100ms in the video. We can find a time that works for the animation as well as doesn't hinder the typing.

Hey @devanshuyadav. I think after correct key press ,"shake" animation should stops immediately!

**Comment by FurqanAnwar** [comment]
@devanshuyadav we need that 0.8s gap between animation and the next letter typed . There must be a work around. If we do it this way than all our effort putting those `setTimeout() function` will  go into vain. It would have been much easier for us if this project was not about this POP UP animation , because of it we had to modify a lot of code like removing the animation after 0.8s using `setTimeout()` etc. So that's why we can not mess up with the animation, this pop up animation is our main requirement keep that in mind

**Comment by FurqanAnwar** [comment]
> I guess this same issue is causing #7

Yup it's all because of this animation as there should be pause like user should be restricted for those 0.8s but right now he isn't restricted that's what causing word to pop out when we immediately press space bar after popping out the word as there is so less time between these two event and no restriction we are having weird results because of it. I am looking at it now and it's will be resolved soon
