### ISSUE TITLE
UI design needs to be improved

### ISSUE THREAD

**Issue by Mishthisinghal** [FurqanAnwar/Typing-Simulator#4]
Can I work on this issue?

**Comment by FurqanAnwar** [comment]
Yes you are most welcome, but before making PR could you share the design or your thought on what the UI should look like and the UI part was left on purpose to deal with it later as you have now asked, we would like you to work on it but before moving on with design do share it  with me so that we can discuss and come up with good UI.

**Comment by Mishthisinghal** [comment]
@FurqanAnwar please take a look at this one
![image](https://user-images.githubusercontent.com/79502029/135991811-bd8d2d29-487c-4eb5-bae1-f21b5d2420ab.png)

**Comment by FurqanAnwar** [comment]
@Mishthisinghal sounds good to me
